name: towerDefMc
version: '1.0-SNAPSHOT'
main: dev.etran.towerDefMc.TowerDefMC
api-version: '1.21'

commands:
  giveTDtower:
    description: A command to give a zombie tower with no AI.
    usage: /<command> [player] [amount]

  giveTDcheckpoint:
    description: A command to give a checkpoint armor stand for enemies.
    usage: /<command> [amount]

  giveTDenemy:
    description: A command to give an enemy spawn with limited AI.
    usage: /<command> [amount]

  giveTDstartpoint:
    description: A command to give a spawn point for the enemies
    usage: /<command>

  giveTDendpoint:
    description: A command to give an end point for the enemies
    usage: /<command>

  clearTDallwaypoints:
    description: A command to clear all startpoints, checkpoints and endpoints
    usage: /<command>

  clearTDalltowers:
    description: A command to clear all existing towers
    usage: /<command>

  clearTDallenemies:
    description: A command to remove all enemies spawned in at the moment
    usage: /<command>

  toggleStandVisibility:
    description: A command to toggle the visibility of all stands
    usage: /<command>

  tdmenu:
    description: Open Tower Defense menus with structured commands
    usage: /<command> <home|new|modify|delete|waves|select> [gameId]
    permission: towerdef.menu
    aliases: [tdm, menu]
