name: towerDefMc
version: '1.0-SNAPSHOT'
main: dev.etran.towerDefMc.TowerDefMC
api-version: '1.21'
depend: [NBTAPI]

commands:
  spawnegg:
    description: A command to give spawnegg.
    usage: /<command> [player] [amount]