name: towerDefMc
version: '1.0-SNAPSHOT'
main: dev.etran.towerDefMc.TowerDefMC
api-version: '1.21'
depend: [NBTAPI]

commands:
  givettower:
    description: A command to give a zombie tower with no AI.
    usage: /<command> [player] [amount]

  givetcheckpoint:
    description: A command to give a checkpoint armor stand for enemies.
    usage: /<command> [amount]