name: towerDefMc
version: '1.0-SNAPSHOT'
main: dev.etran.towerDefMc.TowerDefMC
api-version: '1.21'

commands:
  givettower:
    description: A command to give a zombie tower with no AI.
    usage: /<command> [player] [amount]

  givetcheckpoint:
    description: A command to give a checkpoint armor stand for enemies.
    usage: /<command> [amount]

  givetenemy:
    description: A command to give an enemy spawn with limited AI.
    usage: /<command> [amount]

  givetstartpoint:
    description: A command to give a spawn point for the enemies
    usage: /<command>

  givetendpoint:
    description: A command to give an end point for the enemies
    usage: /<command>

  cleartallcheckpoints:
    description: A command to clear all checkpoints and endpoints
    usage: /<command>